const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet
	];
};
self.C3_JsPropNameTable = [
	{Mosaico: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sólido: 0},
	{plataforma: 0},
	{Piscar: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Plataforma: 0},
	{caixa: 0},
	{porta: 0},
	{chave: 0},
	{bomba: 0},
	{CentrarEm: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{sensorSolido: 0},
	{Teclado: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{direção: 0},
	{porcopatrulheiro: 0},
	{Sprite13: 0},
	{sensorPatrulheirodireita: 0},
	{sensorPatrulheiroesquerda: 0},
	{porcocanhão: 0},
	{canhão: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{Girar: 0},
	{bala: 0},
	{sensorcanhão: 0},
	{vida: 0},
	{itenshud: 0},
	{black: 0},
	{jogadordialogo: 0},
	{FonteDeSprites: 0},
	{chefao: 0},
	{Áudio: 0},
	{vidas: 0}
];

self.InstanceType = {
	Mosaico: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	plataforma: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	sensorSolido: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	porcopatrulheiro: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	sensorPatrulheirodireita: class extends self.ISpriteInstance {},
	sensorPatrulheiroesquerda: class extends self.ISpriteInstance {},
	porcocanhão: class extends self.ISpriteInstance {},
	canhão: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	sensorcanhão: class extends self.ISpriteInstance {},
	vida: class extends self.ISpriteInstance {},
	itenshud: class extends self.ISpriteInstance {},
	black: class extends self.ISpriteInstance {},
	jogadordialogo: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	chave: class extends self.ISpriteInstance {},
	bomba: class extends self.ISpriteInstance {},
	chefao: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {}
}